var GAME_LEVELS = [
  ["                                                                                                                       ",
   "                                                                                                                       ",
   "                                                                                                                       ",
   "                                                                                                                       ",
   "                                                                                                                       ",
   "                                      x   k     oooooooooooo          x                                                ",
   "                                      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                ",
   "            x oooo           k x                                                                                       ",
   "            xxxxxxx!!!!!!xxxxxxx                                                                                       ",
   "            xxxxxxxxxvxxxxxxxxxx                                       x oooo          k  x                           x",
   "                                   xooo   k x                          xxxxxxxs s ssxxxxxxx                           x",
   "                                   xxxxxxxxxx                          xxxxxxxxxxxxxxxxxxxx                           x",
   "                                                                                                                      x",
   "                                                x   k  x                                              oooo            x",
   "  xx                    ooooo            y      xxxxxxxx                                  x!!!|!|!!xxxxxxxxxx         x",
   "  x                                                                                       xxxxxxxxxxxxxxxxxxx         x",
   "  x                  xxxxxxxxxx                                                                                       x",
   "  x                                    xxxxx                                                                          x",
   "  x  @                      oooooo   xxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxx                               f x",
   "  xxxxxxxxxxxxxxxx!||!!!xxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxx",
   "                xx!!!!!!xx                xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     x!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxx",
   "                xx!!!!!!xx                xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                xx!!!!!!xx                 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                        ",
   "                 xxxxxxxx                                                                                              ",
   "                                                                                                                       ",
   "                                                                                                                       "],
  ["                                                                                                                                                  ",
   "                                                                                                                                                  ",
   "                                                                                                                                                  ",
   "                                                                                                                                                  ",
   "               oooo                                   oooooo                                                                                      ",
   "                                                                                                                                                  ",
   "         xxxxxxxxx    xxxxxxxx!|!|!xxxxx!|!xxxx!|!xxxxx   xxxx                                                                                    ",
   "                  ssss       xxxxxxx    xxxxxxxxxxx   ssss            oo                             oooooo                                       ",
   "oo                                                                  x   k              x     x       k       x                                    ",
   "xxxx                                                                xxxxxxxx!!!!xxxxxxxx     xxxxxxxxxxxxxxxxx                                    ",
   "                                                                           xxxxxx                                        ooooo                    ",
   "                                                                                                                                                  ",
   "!!!!!!xxxxxxx       ooooooo                                                                                   x!!!!!xxxxxxxxxxxx                  ",
   "xxxxxxx                                                x!!!!!!!!!!!!!!!!x                                     xxvxxxx           ss          ooooo ",
   "                 xxxxxx                                xxxxxxxvxxxvxxxxxx                                                             x        k x",
   "                      x                                                                                                               xxxxxxxxxxxx",
   "                      x   xxx                                                                                                                     ",
   "x                      sss                                                                                                                        ",
   "x                                              o                                                                           oooo                   ",
   "x                             x               k   x        oo   o   o                                                                             ",
   "x                             xxxxxxx!!!!!xxxxxxxxx                                                                   xxxxxxsssxxxxxx!!!!!!!!!!!!!",
   "x                                  xxxxxxxx              x           x                                                              xxxxxxxxxxxxxx",
   "x                                                        xxxxxxxxxxxxx                                     oooooooo                               ",
   "x                                       oooooooooo                                                   x   k              x                        x",
   "x                                                                                                    xxxxxxxxxxxxxxxxxxxx                        x",
   "x                oooo        xxxxxxxxxxxxxxxxxxxxxxxxxxx                                                                                         x",
   "x                                                                                                                               oooooo           x",
   "x             xxxxxxxxxxx                                                                                                                        x",
   "x  @                                                                                                                                         f   x",
   "xxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["                          x                                                                                   ",
   "                          x                                                                                   ",
   "      oooo                x                                                                                   ",
   "  @                       x                                                                                   ",
   "xxxxxxxxxxxxxx            x              x    k          k   x                                                ",
   "                          x              xxxxxxxxxxxxxxxxxxxxx                  oooooooo                      ",
   "                          x           xxxx            x                                                       ",
   "                 o        x                           x           x     k      x   xxx   x    k  x            ",
   "                  oo      x   k    x                  x           xxxxxxxxxxxxxx!|!xxx!|!xxxxxxxxxx           ",
   "                   ooooo  xxxxxxxxxx                  x                        xxxxxxxxxx                     ",
   "                          x           oooooo          x!!!!!!!!!!!!                                           ",
   "            x       k     x          xxxxxxxxxx       xxxxxxxxxxxxx          ooo                  oooooo      ",
   "            xxxxxxxxxxxxxxx        xxx                x                  x                           k        ",
   "                          x ooo                       x                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                          xxxxx                       x                                                       ",
   "                          x   xxxx                    x                                                       ",
   "                          x                           x  oooooooo                                             ",
   "                          x    x    k   x             xxxxxxxxxxxxxx!!!||!!!xxxxxx                            ",
   "  ooooo                   x    xxxxxxxxxx       ooo   x            xxvxxxxxxx                                 ",
   "                          x                           x                                                       ",
   "xxxxxxxx!!|!!xxxxx        x                  xxxxxxxxxx                                               oooo    ",
   "       xxxxxxx            x                           x             oooooooo                                  ",
   "                          x        xxxxxx             x         x         k                             k     ",
   "                          x                           x         xxxxxxxxxxxxxxxx!!!xxx!|||!xxxxxxxxxxxxxxxxxxx",
   "                          x                 xxx!!!!!!!x                        xxxxxxxxxxxxx                  ",
   "                          x                    xxxvxxxx                                                       ",
   "                x    k    x   oooooooooo              x                                                       ",
   "                xxxxxxxxxxxxxxxxxxxxxxxx        oooo  x                                                       ",
   "                                                      x         ooooooooooo                                   ",
   "                                            xx    k   x     xxxxxxxxxxxxxxxxx                                 ",
   "          oooooo         ooooooooooooo       xxxxxxxxxx                                                       ",
   "                                                                                                oo            ",
   "   x           k               k          x                                                                   ",
   "   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                         x            k        f   x",
   "                                                                                    xxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              ",
   "                                                                                                              ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                  oooooooooooooooooooooooooo                                                  ",
   "                                                                                                              ",
   "               oooooo                                                                                         ",
   " oo                xxxxxss|ssxxxxx    xxxxxxxxxxxx    xxxxxxxxx                                               ",
   "                                  ssss            ssss        x                                               ",
   "xxxxx!!!|!!xxxxx                                              x                                               ",
   "xxxxxxxxxxxx    sssxxxxx                                      x                oooo                           ",
   "                                 ooooooo                      xxxxxx!!!|!!|!!xxxxxxxx                         ",
   "                     x        k           x                   x    xxxxxxxxxxx                                ",
   "    ooooooo          xxxxxxxxxxxxxxxxxxxxxx                   x                                               ",
   "x       k      x                                              x                                ooooooooo      ",
   "xxxxxxxxxxxxxxxx                                              x                          x          k        x",
   "                                                              x                          xxxxxxxxxxxxxxxxxxxxx",
   "                 xxxxxxxx!!!!!!!!!!!!!!x                      x                                               ",
   "                        xxxvxxxxxvxxxxxx                      x                                               ",
   "                                                              x         ooooo                                 ",
   "       xxxxxx   xxx     oooooooooo                            x       xxxxxxxx     xxxxxx                     ",
   "             sss                                              x               sssss                           ",
   "                   x        k        x                        x                                               ",
   "                   xxxxxxxxxxxxxxxxxxx       x k x            x                      ooooo                    ",
   "                                             xxxxx            x!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxx    xxxx        ",
   "               oooo                          ooooooo          xxxxxxxxxxxxxxxxxxxxx           ssss            ",
   "                                                              x                                               ",
   "          xxxxxxxxxxxxxxx     xxxx!!!xxxx    xxxxxxxxxxx      x                                               ",
   "                                                              x                                     ooooo     ",
   "     oooooo                                                   x                               xxxxxxxxxxxxxxxx",
   "xxxxxxxxxxx   xx                                              x                                               ",
   "           sss           oooooooo                             x                                               ",
   "                     x      k      x                          x                        x   k    x             ",
   "                     xxxxxxxxxxxxxxx                              ooooooooo           xxxxxxxxxxx       ooo   ",
   "  @                                                                                                         f ",
   "xxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!||!!!xxxxxxxxxxxxxxxxxxxxx!!!!!||||||!!!!!xxxxxxxxxx"]
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "           xx!!!!!xx      xxx     xx!!!!xx       xx!!!!!!!!!!!!xx     xxx     xxxxx!!!!!!xx    xxx            ",
   "            xx!!!xx      xx!xx    xx!!!!xx       xx!!!!!!!!!!!!xx     xxx     xx xxx!!!!!xx    xxx            ",
   "             xx!xx      xx!!!xx   xx!!!!xx       xx!!!!!!!!!!!!xx     xxx     xx  xxx!!!!xx    xxx            ",
   "              xxx       xx!!!xx   xx!!!!xx        xx!!!!xx!!!!xx      xxx     xx    xx!!!xx    xxx            ",
   "              xxx        xx!xx     xx!!xx          xx!!xxxx!!xx       xxx     xx     xx!xxx                   ",
   "              xxx         xxx       xxxx            xxxx  xxxx        xxx     xx      xxxxx    xxx            ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
   "oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
   "oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
   "oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
   "                                                        @                                                     ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
   ];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
